version: '3.8'

services:
  database:
    build:
      context: ./backend
    container_name: ${CONTAINER_NAME}
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ${NETWORK_NAME}
volumes:
  postgres_data:

networks:
  carbon-network:
    name: ${NETWORK_NAME}
