- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Deploy nginx.conf
  copy:
    src: ../../infra/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx
